services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: doucine-backend
    restart: unless-stopped
    volumes:
      - ./data:/usr/src/app/data
    environment:
      - NODE_ENV=production
      - PORT=3000
      - JWT_SECRET=${JWT_SECRET:-secret_jwt_a_changer_en_production}
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/v2/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.doucine-api.rule=Host(`api.association-doucine.fr`)"
      - "traefik.http.routers.doucine-api.entrypoints=websecure"
      - "traefik.http.routers.doucine-api.tls.certresolver=letsencrypt"
      - "traefik.http.services.doucine-api.loadbalancer.server.port=3000"
    networks:
      - traefik-public

  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: unless-stopped
    ports:
      - "8080:80"  
      - "8443:443" 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/acme.json:/acme.json
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-dashboard.rule=Host(`traefik.association-doucine.fr`)"
      - "traefik.http.routers.traefik-dashboard.entrypoints=websecure"
      - "traefik.http.routers.traefik-dashboard.tls.certresolver=letsencrypt"
      - "traefik.http.routers.traefik-dashboard.service=api@internal"
      - "traefik.http.routers.traefik-dashboard.middlewares=traefik-auth"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_AUTH:-admin:$$apr1$$1UZPNQqT$$Ckz3LJpVgCGfgUwjLuIGG/}"

networks:
  traefik-public:
    external: false
