[build]
  command = "npm run build"
  publish = "dist"

# Redirection pour le routage Vue.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configuration des en-têtes de sécurité
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block" 