[build]
  command = "npm run build"
  publish = "dist"

# Forcer HTTPS
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

# Redirection pour le routage Vue.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Variables d'environnement pour la production
[context.production.environment]
  VUE_APP_API_URL = "https://cms-doucine.up.railway.app"

# Variables d'environnement pour le déploiement de preview
[context.deploy-preview.environment]
  VUE_APP_API_URL = "https://cms-doucine.up.railway.app"

# Configuration des en-têtes de sécurité
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Content-Security-Policy = "upgrade-insecure-requests" 