[build]
  command = "npm install && npm run build"
  publish = "dist"
  environment = { NODE_VERSION = "18" }

# Proxy pour l'API
[[redirects]]
  from = "/api/*"
  to = "http://51.159.180.252/api/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

# Redirection pour le routage Vue.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configuration des en-têtes de sécurité
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' data: https:; img-src 'self' data: https:;"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin" 