[build]
  command = "npm install && npm run build"
  publish = "dist"
  environment = { NODE_VERSION = "18" }

# Proxy pour la nouvelle API v2 (Node.js/TypeScript)
[[redirects]]
  from = "/api/v2/*"
  to = "http://51.159.180.252/api/v2/:splat"
  status = 200
  force = true
  [headers]
    Access-Control-Allow-Origin = "*"

# Proxy pour l'API Strapi existante (v1)
[[redirects]]
  from = "/api/*"
  to = "http://51.159.180.252/api/:splat"
  status = 200
  force = true
  [headers]
    Access-Control-Allow-Origin = "*"
  
# Gestion des requêtes OPTIONS (CORS preflight)
[[redirects]]
  from = "/api/*"
  to = "http://51.159.180.252/api/:splat"
  status = 204
  force = true
  [headers]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS, PATCH"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"
    Access-Control-Max-Age = "86400"
  [conditions]
    Methods = ["OPTIONS"]

# Redirection pour le routage Vue.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configuration des en-têtes de sécurité
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' data: https:; img-src 'self' data: https:;"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin" 